### ISSUE TITLE
There should be an endpoint that Nexmo should report the result of the fitting time question to

### ISSUE THREAD

**Issue by bolorundurowb** [bolorundurowb/project-fitted#118]
Endpoint: `/orders/fitting-time`

If the tailor rejects all suggested fitting times, then an email should be sent to the customer asking them to select three new fitting times

If the tailor accepts any of the given times, then it should be recorded in the database

**Comment by Saint-lawal** [comment]
{ dtmf: '',
2017-09-06T16:57:13.395844+00:00 app[web.1]:   timed_out: true,
2017-09-06T16:57:13.395845+00:00 app[web.1]:   uuid: null,
2017-09-06T16:57:13.395846+00:00 app[web.1]:   conversation_uuid: 'CON-acbd7380-f892-478b-8236-134ae3ffeb9b' }

default nexmo object

**Comment by bolorundurowb** [comment]
@adetola-ralph is this still a valid task?

**Comment by Saint-lawal** [comment]
@bolorundurowb yes in fact it is the next important task

**Comment by adetola-ralph** [comment]
working on it now
