### ISSUE TITLE
Add authentication middleware

### ISSUE THREAD

**Issue by bolorundurowb** [bolorundurowb/project-fitted#26]
The middleware should
- check for a token either `x-access-token` or `token` in the header
- decode the token 
- check if the user is valid
- if all checks out , append the customer or tailor (instead of the user model)  to `req.user`

**Comment by adetola-ralph** [comment]
@bolorundurowb have we decided how this will look like?

**Comment by bolorundurowb** [comment]
@adetola-ralph I think for simplicity and cross team understanding, lets go with the conventional way we write routes and middleware

**Comment by bolorundurowb** [comment]
@adetola-ralph I have updated this story
