### ISSUE TITLE
A customer should be able to create an order

### ISSUE THREAD

**Issue by bolorundurowb** [bolorundurowb/project-fitted#30]
When I make a `POST` request to the route `/api/orders`

*Request*

```json
{
  "outfitType": "xxxxx",
  "fittingDate": "xxxx",
  "deliveryDate": "xxxxxx"
}
```

*Response*

```json
{
  "message": "xxxxx"
}
```

**Comment by adetola-ralph** [comment]
Yo @bolorundurowb is user only customer in this task

**Comment by bolorundurowb** [comment]
Yes @adetola-ralph I have renamed the task as appropriate

**Comment by adetola-ralph** [comment]
@bolorundurowb what is the data type for outfitType?

**Comment by bolorundurowb** [comment]
@adetola-ralph its a `String` I believe
