### ISSUE TITLE
As a user when it is time for fitting, I should get a message asking if my fitting has started

### ISSUE THREAD

**Issue by bolorundurowb** [bolorundurowb/project-fitted#37]
if the user answers `yes` then a 1 hour timer is started. 
if the user answers `no` then the tailor should be marked as `late`.

**Comment by Saint-lawal** [comment]
Yo @bolorundurowb @adetola-ralph I can't do this yet cause we are yet to create the fitting date

**Comment by bolorundurowb** [comment]
Hey, man @Saint-lawal the fitting date is live in the model. I need this implemented so I can implement my own task. thanks

**Comment by Saint-lawal** [comment]
@bolorundurowb I need 118 to be done before I do mine

**Comment by bolorundurowb** [comment]
hey man @Saint-lawal #118 has been done. Want to proceed with this?

**Comment by bolorundurowb** [comment]
stale
