### ISSUE TITLE
create logging class

### ISSUE THREAD

**Issue by bolorundurowb** [bolorundurowb/project-fitted#45]
make use of `winston`

- To log to the console, I should be able to call `Logger.log()`
- To log an error to file, I should be able to call `Logger.error()`

**Comment by Saint-lawal** [comment]
More like logger.error() and logger.info(), yes? @bolorundurowb

**Comment by bolorundurowb** [comment]
@Saint-lawal when we import it, since we are using classes, we'd have to import it as `Logger`
