### ISSUE TITLE
A customer should be able to select a tailor for an order

### ISSUE THREAD

**Issue by adetola-ralph** [bolorundurowb/project-fitted#88]

**Comment by adetola-ralph** [comment]
Order should be of status await-match

**Comment by adetola-ralph** [comment]
Ideally this will be selected from a map showing a list of tailors around the customer

**Comment by Saint-lawal** [comment]
So shouldn't this be more like "A customer should be able to get all tailors matching a category/subcategory specification"? @adetola-ralph @bolorundurowb

**Comment by bolorundurowb** [comment]
@Saint-lawal thing is those category and sub-category options can be added a queries to the `/tailors/nearby` endpoint. I am not 100% sure on that. please confirm
